project:
  type: website
  output-dir: docs

website:
  title: "FlipR-data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/FlipR-data

format:
  html:
    theme: [flatly, custom.scss]
    code-fold: true
    code-tools: true
    toc: true

editor: visual